Capture a potentially interesting Rust compiler output
$ cargo test
   Compiling dominant_colours v1.0.0 (/Users/alexwlchan/repos/dominant_colours)
error[E0106]: missing lifetime specifier
   --> src/main.rs:167:17
    |
167 |         stdout: &str,
    |                 ^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
165 |     struct DcOutput<'a> {
166 |         exit_code: i32,
167 |         stdout: &'a str,
    |

error[E0106]: missing lifetime specifier
   --> src/main.rs:168:17
    |
168 |         stderr: &str,
    |                 ^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
165 |     struct DcOutput<'a> {
166 |         exit_code: i32,
167 |         stdout: &str,
168 |         stderr: &'a str,
    |

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0106`.
error: could not compile `dominant_colours`

To learn more, run the command again with --verbose.